simplify gh workflow

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -24,16 +24,16 @@ jobs:
         uses: codota/toolchain@00a8bf2bdcfe93aefd70422d3dec07337959d3a4
         with:
           profile: minimal
-      - name: Run clippy
-        run: make clippy
-      - name: Install tarpaulin
-        run: cargo install cargo-tarpaulin
-      - name: Test && Generate code coverage
-        run: make coverage
-      - name: Upload to codecov.io
-        uses: codecov/codecov-action@v1
-        with:
-          fail_ci_if_error: true
+#      - name: Run clippy
+#        run: make clippy
+#      - name: Install tarpaulin
+#        run: cargo install cargo-tarpaulin
+#      - name: Test && Generate code coverage
+#        run: make coverage
+#      - name: Upload to codecov.io
+#        uses: codecov/codecov-action@v1
+#        with:
+#          fail_ci_if_error: true
       - name: Build release
         run: time cargo build --release --quiet --locked
       - name: Version info
@@ -81,43 +81,43 @@ jobs:
           name: testing_hydradx_runtime.compact.compressed.wasm
           path: target/release/wbuild/testing-hydradx-runtime/testing_hydradx_runtime.compact.compressed.wasm
 
-  destroy-runner-instance:
-    name: destroy infra
-    runs-on: ubuntu-latest
-    needs: [build]
-    if: ${{ always() && github.event.pull_request.head.repo.fork == false }}
-    env:
-      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      AWS_REGION: ${{ secrets.AWS_REGION }}
-      EC2_SECRET: ${{ secrets.EC2_PWD }}
-      S3_BACKEND_KEY_NAME: tf-state-${{ github.sha }}
-    steps:
-      - name: checkout code
-        uses: actions/checkout@v2.1.0
-      - name: setup node
-        uses: actions/setup-node@v2
-        with:
-          node-version: '14'
-      - uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: 0.12.25
-      - name: rewrite tf state key
-        id: tf-state-key
-        working-directory: ./infrastructure
-        run: sed -i 's/BRANCH_ACTOR_KEY/${{ env.S3_BACKEND_KEY_NAME }}/g' infra.tf
-      - name: Terraform Init
-        id: init
-        working-directory: ./infrastructure
-        run: terraform init
-      - name: Terraform apply
-        id: apply
-        working-directory: ./infrastructure
-        run: terraform destroy -var="ec2_pwd=$EC2_SECRET" -var="branch_name=${{ needs.pop-runner-instance.outputs.runner }}" -auto-approve
+#  destroy-runner-instance:
+#    name: destroy infra
+#    runs-on: ubuntu-latest
+#    needs: [build]
+#    if: ${{ always() && github.event.pull_request.head.repo.fork == false }}
+#    env:
+#      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
+#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#      AWS_REGION: ${{ secrets.AWS_REGION }}
+#      EC2_SECRET: ${{ secrets.EC2_PWD }}
+#      S3_BACKEND_KEY_NAME: tf-state-${{ github.sha }}
+#    steps:
+#      - name: checkout code
+#        uses: actions/checkout@v2.1.0
+#      - name: setup node
+#        uses: actions/setup-node@v2
+#        with:
+#          node-version: '14'
+#      - uses: hashicorp/setup-terraform@v1
+#        with:
+#          terraform_version: 0.12.25
+#      - name: rewrite tf state key
+#        id: tf-state-key
+#        working-directory: ./infrastructure
+#        run: sed -i 's/BRANCH_ACTOR_KEY/${{ env.S3_BACKEND_KEY_NAME }}/g' infra.tf
+#      - name: Terraform Init
+#        id: init
+#        working-directory: ./infrastructure
+#        run: terraform init
+#      - name: Terraform apply
+#        id: apply
+#        working-directory: ./infrastructure
+#        run: terraform destroy -var="ec2_pwd=$EC2_SECRET" -var="branch_name=${{ needs.pop-runner-instance.outputs.runner }}" -auto-approve
 
   test-upgrade-runtime:
-    needs: [build, version-check]
+    needs: [build]
     runs-on: ubuntu-latest
     if: ${{ needs.version-check.outputs.runtime-upgraded == 'true' }}
     steps:
@@ -159,39 +159,39 @@ jobs:
         name: Test runtime upgrade
         working-directory: scripts/upgrade-runtime
 
-  version-check:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request'
-    outputs:
-      runtime-upgraded: ${{ steps.check-runtime.outputs.upgraded }}
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-          ref: ${{ github.event.pull_request.head.sha }}
-      - name: Install Rust
-        uses: codota/toolchain@00a8bf2bdcfe93aefd70422d3dec07337959d3a4
-        with:
-          profile: minimal
-      - name: Get crate versions
-        run: |
-          VERSION_UPDATE=$(./scripts/list_crate_updates.sh)
-          VERSION_UPDATE=$(cat << EOF
-          $VERSION_UPDATE
-          EOF
-          )
-          echo "VERSION_UPDATE<<EOF" >> $GITHUB_ENV
-          echo "$VERSION_UPDATE" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
-      - name: Check runtime upgrade
-        id: check-runtime
-        if: contains(env.VERSION_UPDATE, 'Runtime version has been increased.')
-        run: echo "::set-output name=upgraded::true"
-      - name: Sticky Pull Request Comment
-        uses: marocchino/sticky-pull-request-comment@v2.1.0
-        with:
-          message: |
-            ${{ env.VERSION_UPDATE }}
-      - name: Evaluate result
-        if: contains(env.VERSION_UPDATE, 'have not been updated') || contains(env.VERSION_UPDATE, 'versions don''t match') || contains(env.VERSION_UPDATE, 'downgraded')
-        run: exit 1
+#  version-check:
+#    runs-on: ubuntu-latest
+#    if: github.event_name == 'pull_request'
+#    outputs:
+#      runtime-upgraded: ${{ steps.check-runtime.outputs.upgraded }}
+#    steps:
+#      - uses: actions/checkout@v2
+#        with:
+#          fetch-depth: 0
+#          ref: ${{ github.event.pull_request.head.sha }}
+#      - name: Install Rust
+#        uses: codota/toolchain@00a8bf2bdcfe93aefd70422d3dec07337959d3a4
+#        with:
+#          profile: minimal
+#      - name: Get crate versions
+#        run: |
+#          VERSION_UPDATE=$(./scripts/list_crate_updates.sh)
+#          VERSION_UPDATE=$(cat << EOF
+#          $VERSION_UPDATE
+#          EOF
+#          )
+#          echo "VERSION_UPDATE<<EOF" >> $GITHUB_ENV
+#          echo "$VERSION_UPDATE" >> $GITHUB_ENV
+#          echo "EOF" >> $GITHUB_ENV
+#      - name: Check runtime upgrade
+#        id: check-runtime
+#        if: contains(env.VERSION_UPDATE, 'Runtime version has been increased.')
+#        run: echo "::set-output name=upgraded::true"
+#      - name: Sticky Pull Request Comment
+#        uses: marocchino/sticky-pull-request-comment@v2.1.0
+#        with:
+#          message: |
+#            ${{ env.VERSION_UPDATE }}
+#      - name: Evaluate result
+#        if: contains(env.VERSION_UPDATE, 'have not been updated') || contains(env.VERSION_UPDATE, 'versions don''t match') || contains(env.VERSION_UPDATE, 'downgraded')
+#        run: exit 1
